// 고정 꽃(아이템) 목록.
// name: 스크린샷 이름 배너에서 추출, 사용자 확정.
// grade: 이름 배너 배경색 — "UR"(빨간꽃) / "SSR"(노란꽃) / "SR"(보라꽃).
// image: assets/flowers/ 경로.
export const FLOWERS = [
  { id: "flower-01", name: "무지개 오리의 즐거운 산책", image: "assets/flowers/flower-01.png", grade: "SSR" },
  { id: "flower-02", name: "골든 스프링", image: "assets/flowers/flower-02.png", grade: "SSR" },
  { id: "flower-03", name: "보랏빛 구름의 안식", image: "assets/flowers/flower-03.png", grade: "SSR" },
  { id: "flower-04", name: "황금빛 단꿈", image: "assets/flowers/flower-04.png", grade: "SSR" },
  { id: "flower-05", name: "푸른 물결의 춤", image: "assets/flowers/flower-05.png", grade: "SSR" },
  { id: "flower-06", name: "학월성덩굴", image: "assets/flowers/flower-06.png", grade: "SSR" },
  { id: "flower-07", name: "차와 야옹 이야기", image: "assets/flowers/flower-07.png", grade: "SSR" },
  { id: "flower-08", name: "꽃케이크 바구니", image: "assets/flowers/flower-08.png", grade: "SSR" },
  { id: "flower-09", name: "성란화의 언약", image: "assets/flowers/flower-09.png", grade: "SSR" },
  { id: "flower-10", name: "파스텔 꿈의 조개", image: "assets/flowers/flower-10.png", grade: "SSR" },
  { id: "flower-11", name: "가을빛 단풍", image: "assets/flowers/flower-11.png", grade: "SSR" },
  { id: "flower-12", name: "달빛 모란", image: "assets/flowers/flower-12.png", grade: "SSR" },
  { id: "flower-13", name: "귤빛 불꽃 부용", image: "assets/flowers/flower-13.png", grade: "SSR" },
  { id: "flower-14", name: "분홍옥 부용", image: "assets/flowers/flower-14.png", grade: "SSR" },
  { id: "flower-15", name: "보랏빛 꿈 부용", image: "assets/flowers/flower-15.png", grade: "SSR" },
  { id: "flower-16", name: "먹빛 모란", image: "assets/flowers/flower-16.png", grade: "SSR" },
  { id: "flower-17", name: "선녀의 춤", image: "assets/flowers/flower-17.png", grade: "SSR" },
  { id: "flower-18", name: "봄 살구빛 옷자락", image: "assets/flowers/flower-18.png", grade: "SSR" },
  { id: "flower-19", name: "푸른안개 모란", image: "assets/flowers/flower-19.png", grade: "SSR" },
  { id: "flower-20", name: "분홍빛 물결꽃", image: "assets/flowers/flower-20.png", grade: "SSR" },
  { id: "flower-21", name: "자색 여운", image: "assets/flowers/flower-21.png", grade: "SSR" },
  { id: "flower-22", name: "비령추란", image: "assets/flowers/flower-22.png", grade: "SSR" },
  { id: "flower-23", name: "몽롱한 청아", image: "assets/flowers/flower-23.png", grade: "SSR" },
  { id: "flower-24", name: "황금 장미", image: "assets/flowers/flower-24.png", grade: "SSR" },
  { id: "flower-25", name: "수정빛 나비춤 장미", image: "assets/flowers/flower-25.png", grade: "SSR" },
  { id: "flower-26", name: "진홍빛 납매", image: "assets/flowers/flower-26.png", grade: "SSR" },
  { id: "flower-27", name: "홍운 납매", image: "assets/flowers/flower-27.png", grade: "SSR" },
  { id: "flower-28", name: "크리스마스의 밤", image: "assets/flowers/flower-28.png", grade: "SSR" },
  { id: "flower-29", name: "행운의 올리브", image: "assets/flowers/flower-29.png", grade: "SSR" },
  { id: "flower-30", name: "별빛 꿈의 방주", image: "assets/flowers/flower-30.png", grade: "SSR" },
  { id: "flower-31", name: "냥이의 즐거운 노래", image: "assets/flowers/flower-31.png", grade: "SSR" },
  { id: "flower-32", name: "심쿵 스위트 베리", image: "assets/flowers/flower-32.png", grade: "SSR" },
  { id: "flower-33", name: "황소자리·풍요의 별그림", image: "assets/flowers/flower-33.png", grade: "UR" },
  { id: "flower-34", name: "별똥별의 향기", image: "assets/flowers/flower-34.png", grade: "UR" },
  { id: "flower-35", name: "옥구슬 목련", image: "assets/flowers/flower-35.png", grade: "SSR" },
  { id: "flower-36", name: "성스러운 깃털의 수호", image: "assets/flowers/flower-36.png", grade: "UR" },
  { id: "flower-37", name: "프로스팅 마녀", image: "assets/flowers/flower-37.png", grade: "UR" },
  { id: "flower-38", name: "나른한 시간", image: "assets/flowers/flower-38.png", grade: "UR" },
  { id: "flower-39", name: "구름꿈 고래의 노래", image: "assets/flowers/flower-39.png", grade: "UR" },
  { id: "flower-40", name: "동화의 성", image: "assets/flowers/flower-40.png", grade: "UR" },
  { id: "flower-41", name: "푸른 사슴 그림자", image: "assets/flowers/flower-41.png", grade: "UR" },
  { id: "flower-42", name: "피어나는 동심", image: "assets/flowers/flower-42.png", grade: "UR" },
  { id: "flower-43", name: "쌍둥이자리·성수쌍영", image: "assets/flowers/flower-43.png", grade: "UR" },
  { id: "flower-44", name: "연핑크 델피니움", image: "assets/flowers/flower-44.png", grade: "SR" },
  { id: "flower-45", name: "연노랑 마거리트", image: "assets/flowers/flower-45.png", grade: "SR" },
  { id: "flower-46", name: "귤홍 윙윙 장미", image: "assets/flowers/flower-46.png", grade: "SR" },
  { id: "flower-47", name: "새벽빛 목향장미", image: "assets/flowers/flower-47.png", grade: "SR" },
  { id: "flower-48", name: "연하늘 델피니움", image: "assets/flowers/flower-48.png", grade: "SR" },
  { id: "flower-49", name: "붉은 눈 목향장미", image: "assets/flowers/flower-49.png", grade: "SR" },
  { id: "flower-50", name: "붉은 깃털 아마릴리스", image: "assets/flowers/flower-50.png", grade: "SR" },
  { id: "flower-51", name: "황금목 아마릴리스", image: "assets/flowers/flower-51.png", grade: "SR" },
  { id: "flower-52", name: "노을빛 아마릴리스", image: "assets/flowers/flower-52.png", grade: "SR" },
  { id: "flower-53", name: "옥빛 글라디올러스", image: "assets/flowers/flower-53.png", grade: "SR" },
  { id: "flower-54", name: "주황 불꽃 글라디올러스", image: "assets/flowers/flower-54.png", grade: "SR" },
  { id: "flower-55", name: "자색 글라디올러스", image: "assets/flowers/flower-55.png", grade: "SR" },
  { id: "flower-56", name: "먹술 아네모네", image: "assets/flowers/flower-56.png", grade: "SR" },
  { id: "flower-57", name: "묵옥 아네모네", image: "assets/flowers/flower-57.png", grade: "SR" },
  { id: "flower-58", name: "아지랑이빛 장미", image: "assets/flowers/flower-58.png", grade: "SR" },
  { id: "flower-59", name: "맑은 봉우리 장미", image: "assets/flowers/flower-59.png", grade: "SR" },
  { id: "flower-60", name: "꾀꼬리 장미", image: "assets/flowers/flower-60.png", grade: "SR" },
  { id: "flower-61", name: "진홍 진달래", image: "assets/flowers/flower-61.png", grade: "SR" },
  { id: "flower-62", name: "창벽 협죽도", image: "assets/flowers/flower-62.png", grade: "SR" },
  { id: "flower-63", name: "용금 아네모네", image: "assets/flowers/flower-63.png", grade: "SR" },
  { id: "flower-64", name: "향설 목향장미", image: "assets/flowers/flower-64.png", grade: "SR" },
  { id: "flower-65", name: "분홍 복숭아 달리아", image: "assets/flowers/flower-65.png", grade: "SR" },
  { id: "flower-66", name: "분홍구름 코스모스", image: "assets/flowers/flower-66.png", grade: "SR" },
  { id: "flower-67", name: "단풍 온시디움", image: "assets/flowers/flower-67.png", grade: "SR" },
  { id: "flower-68", name: "벚꽃 온시디움", image: "assets/flowers/flower-68.png", grade: "SR" },
  { id: "flower-69", name: "새하얀 조팝나무", image: "assets/flowers/flower-69.png", grade: "SR" },
  { id: "flower-70", name: "금종 개나리", image: "assets/flowers/flower-70.png", grade: "SR" },
  { id: "flower-71", name: "봄빛 심비디움", image: "assets/flowers/flower-71.png", grade: "SR" },
  { id: "flower-72", name: "핑크화이트 심비디움", image: "assets/flowers/flower-72.png", grade: "SR" },
  { id: "flower-73", name: "병아리색 헬레보루스", image: "assets/flowers/flower-73.png", grade: "SR" },
  { id: "flower-74", name: "윤분홍 칼랑코에", image: "assets/flowers/flower-74.png", grade: "SR" },
  { id: "flower-75", name: "자색 맥문동", image: "assets/flowers/flower-75.png", grade: "SR" },
  { id: "flower-76", name: "청영 루위시아", image: "assets/flowers/flower-76.png", grade: "SR" },
  { id: "flower-77", name: "금빛 목련", image: "assets/flowers/flower-77.png", grade: "SR" },
  { id: "flower-78", name: "흑자색 목련", image: "assets/flowers/flower-78.png", grade: "SR" },
  { id: "flower-79", name: "비홍 붓꽃", image: "assets/flowers/flower-79.png", grade: "SR" },
  { id: "flower-80", name: "분홍안개 붓꽃", image: "assets/flowers/flower-80.png", grade: "SR" },
  { id: "flower-81", name: "구름빛 아스틸베", image: "assets/flowers/flower-81.png", grade: "SR" },
  { id: "flower-82", name: "아련한 자색 아스틸베", image: "assets/flowers/flower-82.png", grade: "SR" },
  { id: "flower-83", name: "푸른 수레국화", image: "assets/flowers/flower-83.png", grade: "SR" },
  { id: "flower-84", name: "자색 수레국화", image: "assets/flowers/flower-84.png", grade: "SR" },
  { id: "flower-85", name: "오렌지꿀 버베나", image: "assets/flowers/flower-85.png", grade: "SR" },
  { id: "flower-86", name: "연분홍 버베나", image: "assets/flowers/flower-86.png", grade: "SR" },
  { id: "flower-87", name: "꿈의 보라 으아리", image: "assets/flowers/flower-87.png", grade: "SR" },
  { id: "flower-88", name: "햇살 개양귀비", image: "assets/flowers/flower-88.png", grade: "SR" },
  { id: "flower-89", name: "흑자색 개양귀비", image: "assets/flowers/flower-89.png", grade: "SR" },
  { id: "flower-90", name: "황혼 등나무", image: "assets/flowers/flower-90.png", grade: "SR" },
  { id: "flower-91", name: "창공빛 등나무", image: "assets/flowers/flower-91.png", grade: "SR" },
  { id: "flower-92", name: "구름자수 작약", image: "assets/flowers/flower-92.png", grade: "SR" },
  { id: "flower-93", name: "달빛 아네모네", image: "assets/flowers/flower-93.png", grade: "SR" },
  { id: "flower-94", name: "연자색 산호꽃", image: "assets/flowers/flower-94.png", grade: "SR" },
  { id: "flower-95", name: "창봉 은목서", image: "assets/flowers/flower-95.png", grade: "SR" },
  { id: "flower-96", name: "진사 단목서", image: "assets/flowers/flower-96.png", grade: "SR" },
  { id: "flower-97", name: "황금잎 금목서", image: "assets/flowers/flower-97.png", grade: "SR" },
  { id: "flower-98", name: "붉은불꽃 아네모네", image: "assets/flowers/flower-98.png", grade: "SR" },
  { id: "flower-99", name: "연홍색 접시꽃", image: "assets/flowers/flower-99.png", grade: "SR" },
  { id: "flower-100", name: "분홍 스파티필룸", image: "assets/flowers/flower-100.png", grade: "SR" },
  { id: "flower-101", name: "흑수정 달리아", image: "assets/flowers/flower-101.png", grade: "SR" },
  { id: "flower-102", name: "진홍색 달리아", image: "assets/flowers/flower-102.png", grade: "SR" },
  { id: "flower-103", name: "우아한 보라 코스모스", image: "assets/flowers/flower-103.png", grade: "SR" },
  { id: "flower-104", name: "연분홍 조팝나무", image: "assets/flowers/flower-104.png", grade: "SR" },
  { id: "flower-105", name: "흑자색 메코놉시스", image: "assets/flowers/flower-105.png", grade: "SR" },
  { id: "flower-106", name: "유벽 메코놉시스", image: "assets/flowers/flower-106.png", grade: "SR" },
  { id: "flower-107", name: "차홍색 헬레보루스", image: "assets/flowers/flower-107.png", grade: "SR" },
  { id: "flower-108", name: "연지빛 헬레보루스", image: "assets/flowers/flower-108.png", grade: "SR" },
  { id: "flower-109", name: "홍시 칼랑코에", image: "assets/flowers/flower-109.png", grade: "SR" },
  { id: "flower-110", name: "분홍 안개 맥문동", image: "assets/flowers/flower-110.png", grade: "SR" },
  { id: "flower-111", name: "서리꽃 맥문동", image: "assets/flowers/flower-111.png", grade: "SR" },
  { id: "flower-112", name: "따뜻한 노랑 루위시아", image: "assets/flowers/flower-112.png", grade: "SR" },
  { id: "flower-113", name: "분홍 수정 루위시아", image: "assets/flowers/flower-113.png", grade: "SR" },
  { id: "flower-114", name: "금서리 붓꽃", image: "assets/flowers/flower-114.png", grade: "SR" },
  { id: "flower-115", name: "꿀처럼 부드러운 달맞이꽃", image: "assets/flowers/flower-115.png", grade: "SR" },
  { id: "flower-116", name: "타오르는 불꽃 레난테라", image: "assets/flowers/flower-116.png", grade: "SR" },
  { id: "flower-117", name: "브룬펠시아", image: "assets/flowers/flower-117.png", grade: "SR" },
  { id: "flower-118", name: "푸른 소철", image: "assets/flowers/flower-118.png", grade: "SR" },
  { id: "flower-119", name: "우아한 보랏빛 알리움", image: "assets/flowers/flower-119.png", grade: "SR" },
  { id: "flower-120", name: "분홍 수레국화", image: "assets/flowers/flower-120.png", grade: "SR" },
  { id: "flower-121", name: "별꿈 해파리", image: "assets/flowers/flower-121.png", grade: "SR" },
  { id: "flower-122", name: "윤기나는 작약", image: "assets/flowers/flower-122.png", grade: "SR" },
  { id: "flower-123", name: "달계곡 등나무", image: "assets/flowers/flower-123.png", grade: "SR" },
  { id: "flower-124", name: "방울의 가벼운 춤", image: "assets/flowers/flower-124.png", grade: "SR" },
  { id: "flower-125", name: "초승달의 고요한 잠", image: "assets/flowers/flower-125.png", grade: "SR" },
  { id: "flower-126", name: "취한 별의 꿈", image: "assets/flowers/flower-126.png", grade: "SR" },
  { id: "flower-127", name: "연지 무궁화", image: "assets/flowers/flower-127.png", grade: "SR" },
  { id: "flower-128", name: "윤생 호랑가시나무", image: "assets/flowers/flower-128.png", grade: "SR" },
  { id: "flower-129", name: "반짝 솜토끼", image: "assets/flowers/flower-129.png", grade: "SR" },
  { id: "flower-130", name: "연지 아네모네", image: "assets/flowers/flower-130.png", grade: "SR" },
  { id: "flower-131", name: "연지 작약", image: "assets/flowers/flower-131.png", grade: "SR" },
  { id: "flower-132", name: "노을빛 산호꽃", image: "assets/flowers/flower-132.png", grade: "SR" },
  { id: "flower-133", name: "베들레헴의 별", image: "assets/flowers/flower-133.png", grade: "SR" },
  { id: "flower-134", name: "붉은노을 접시꽃", image: "assets/flowers/flower-134.png", grade: "SR" },
  { id: "flower-135", name: "영롱한 얼음빛 납매", image: "assets/flowers/flower-135.png", grade: "SR" },
  { id: "flower-136", name: "진홍 벚꽃 나비무 장미", image: "assets/flowers/flower-136.png", grade: "SR" },
  { id: "flower-137", name: "푸른빛 달맞이꽃", image: "assets/flowers/flower-137.png", grade: "SR" },
  { id: "flower-138", name: "붉은 벚꽃 달맞이꽃", image: "assets/flowers/flower-138.png", grade: "SR" },
  { id: "flower-139", name: "연분홍 페튜니아", image: "assets/flowers/flower-139.png", grade: "SR" },
  { id: "flower-140", name: "진주 제비난", image: "assets/flowers/flower-140.png", grade: "SR" },
  { id: "flower-141", name: "따스한 여름 햇살", image: "assets/flowers/flower-141.png", grade: "SR" },
  { id: "flower-142", name: "연지빛 개양귀비", image: "assets/flowers/flower-142.png", grade: "SR" },
  { id: "flower-143", name: "창공빛 산호초", image: "assets/flowers/flower-143.png", grade: "SR" },
];
