// 고정 꽃(아이템) 목록.
// name: 스크린샷 이름 배너에서 추출, 사용자 확정.
// grade: 이름 배너 배경색에서 판정 — "UR"(빨간꽃) / "SSR"(노란꽃).
// image: assets/flowers/ 경로.
export const FLOWERS = [
  { id: "flower-01", name: "무지개 오리의 즐거운 산책", image: "assets/flowers/flower-01.png", grade: "SSR" },
  { id: "flower-02", name: "골든 스프링", image: "assets/flowers/flower-02.png", grade: "SSR" },
  { id: "flower-03", name: "보랏빛 구름의 안식", image: "assets/flowers/flower-03.png", grade: "SSR" },
  { id: "flower-04", name: "황금빛 단꿈", image: "assets/flowers/flower-04.png", grade: "SSR" },
  { id: "flower-05", name: "푸른 물결의 춤", image: "assets/flowers/flower-05.png", grade: "SSR" },
  { id: "flower-06", name: "학월성덩굴", image: "assets/flowers/flower-06.png", grade: "SSR" },
  { id: "flower-07", name: "차와 야옹 이야기", image: "assets/flowers/flower-07.png", grade: "SSR" },
  { id: "flower-08", name: "꽃케이크 바구니", image: "assets/flowers/flower-08.png", grade: "SSR" },
  { id: "flower-09", name: "성란화의 언약", image: "assets/flowers/flower-09.png", grade: "SSR" },
  { id: "flower-10", name: "파스텔 꿈의 조개", image: "assets/flowers/flower-10.png", grade: "SSR" },
  { id: "flower-11", name: "가을빛 단풍", image: "assets/flowers/flower-11.png", grade: "SSR" },
  { id: "flower-12", name: "달빛 모란", image: "assets/flowers/flower-12.png", grade: "SSR" },
  { id: "flower-13", name: "귤빛 불꽃 부용", image: "assets/flowers/flower-13.png", grade: "SSR" },
  { id: "flower-14", name: "분홍옥 부용", image: "assets/flowers/flower-14.png", grade: "SSR" },
  { id: "flower-15", name: "보랏빛 꿈 부용", image: "assets/flowers/flower-15.png", grade: "SSR" },
  { id: "flower-16", name: "먹빛 모란", image: "assets/flowers/flower-16.png", grade: "SSR" },
  { id: "flower-17", name: "선녀의 춤", image: "assets/flowers/flower-17.png", grade: "SSR" },
  { id: "flower-18", name: "봄 살구빛 옷자락", image: "assets/flowers/flower-18.png", grade: "SSR" },
  { id: "flower-19", name: "푸른안개 모란", image: "assets/flowers/flower-19.png", grade: "SSR" },
  { id: "flower-20", name: "분홍빛 물결꽃", image: "assets/flowers/flower-20.png", grade: "SSR" },
  { id: "flower-21", name: "자색 여운", image: "assets/flowers/flower-21.png", grade: "SSR" },
  { id: "flower-22", name: "비령추란", image: "assets/flowers/flower-22.png", grade: "SSR" },
  { id: "flower-23", name: "몽롱한 청아", image: "assets/flowers/flower-23.png", grade: "SSR" },
  { id: "flower-24", name: "황금 장미", image: "assets/flowers/flower-24.png", grade: "SSR" },
  { id: "flower-25", name: "수정빛 나비춤 장미", image: "assets/flowers/flower-25.png", grade: "SSR" },
  { id: "flower-26", name: "진홍빛 납매", image: "assets/flowers/flower-26.png", grade: "SSR" },
  { id: "flower-27", name: "홍운 납매", image: "assets/flowers/flower-27.png", grade: "SSR" },
  { id: "flower-28", name: "크리스마스의 밤", image: "assets/flowers/flower-28.png", grade: "SSR" },
  { id: "flower-29", name: "행운의 올리브", image: "assets/flowers/flower-29.png", grade: "SSR" },
  { id: "flower-30", name: "별빛 꿈의 방주", image: "assets/flowers/flower-30.png", grade: "SSR" },
  { id: "flower-31", name: "냥이의 즐거운 노래", image: "assets/flowers/flower-31.png", grade: "SSR" },
  { id: "flower-32", name: "심쿵 스위트 베리", image: "assets/flowers/flower-32.png", grade: "SSR" },
  { id: "flower-33", name: "황소자리·풍요의 별그림", image: "assets/flowers/flower-33.png", grade: "UR" },
  { id: "flower-34", name: "별똥별의 향기", image: "assets/flowers/flower-34.png", grade: "UR" },
  { id: "flower-35", name: "옥구슬 목련", image: "assets/flowers/flower-35.png", grade: "SSR" },
  { id: "flower-36", name: "성스러운 깃털의 수호", image: "assets/flowers/flower-36.png", grade: "UR" },
  { id: "flower-37", name: "프로스팅 마녀", image: "assets/flowers/flower-37.png", grade: "UR" },
  { id: "flower-38", name: "나른한 시간", image: "assets/flowers/flower-38.png", grade: "UR" },
  { id: "flower-39", name: "구름꿈 고래의 노래", image: "assets/flowers/flower-39.png", grade: "UR" },
  { id: "flower-40", name: "동화의 성", image: "assets/flowers/flower-40.png", grade: "UR" },
  { id: "flower-41", name: "푸른 사슴 그림자", image: "assets/flowers/flower-41.png", grade: "UR" },
  { id: "flower-42", name: "피어나는 동심", image: "assets/flowers/flower-42.png", grade: "UR" },
  { id: "flower-43", name: "쌍둥이자리·성수쌍영", image: "assets/flowers/flower-43.png", grade: "UR" },
];
